// Automatically generated by MockGen. DO NOT EDIT!
// Source: service/IDateParser.go

package mock_service

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of IDateParser interface
type MockIDateParser struct {
	ctrl     *gomock.Controller
	recorder *_MockIDateParserRecorder
}

// Recorder for MockIDateParser (not exported)
type _MockIDateParserRecorder struct {
	mock *MockIDateParser
}

func NewMockIDateParser(ctrl *gomock.Controller) *MockIDateParser {
	mock := &MockIDateParser{ctrl: ctrl}
	mock.recorder = &_MockIDateParserRecorder{mock}
	return mock
}

func (_m *MockIDateParser) EXPECT() *_MockIDateParserRecorder {
	return _m.recorder
}

func (_m *MockIDateParser) Parse(str string) string {
	ret := _m.ctrl.Call(_m, "Parse", str)
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockIDateParserRecorder) Parse(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Parse", arg0)
}
