// Automatically generated by MockGen. DO NOT EDIT!
// Source: service/ISalaryParser.go

package mock_service

import (
	gomock "github.com/golang/mock/gomock"
	structures "github.com/moazzamk/moz-tech/structures"
)

// Mock of ISalaryParser interface
type MockISalaryParser struct {
	ctrl     *gomock.Controller
	recorder *_MockISalaryParserRecorder
}

// Recorder for MockISalaryParser (not exported)
type _MockISalaryParserRecorder struct {
	mock *MockISalaryParser
}

func NewMockISalaryParser(ctrl *gomock.Controller) *MockISalaryParser {
	mock := &MockISalaryParser{ctrl: ctrl}
	mock.recorder = &_MockISalaryParserRecorder{mock}
	return mock
}

func (_m *MockISalaryParser) EXPECT() *_MockISalaryParserRecorder {
	return _m.recorder
}

func (_m *MockISalaryParser) Parse(str string) *structures.SalaryRange {
	ret := _m.ctrl.Call(_m, "Parse", str)
	ret0, _ := ret[0].(*structures.SalaryRange)
	return ret0
}

func (_mr *_MockISalaryParserRecorder) Parse(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Parse", arg0)
}
