// Automatically generated by MockGen. DO NOT EDIT!
// Source: service/Storage.go

package mock_service

import (
	gomock "github.com/golang/mock/gomock"
	structures "github.com/moazzamk/moz-tech/structures"
)

// Mock of Storage interface
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *_MockStorageRecorder
}

// Recorder for MockStorage (not exported)
type _MockStorageRecorder struct {
	mock *MockStorage
}

func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &_MockStorageRecorder{mock}
	return mock
}

func (_m *MockStorage) EXPECT() *_MockStorageRecorder {
	return _m.recorder
}

func (_m *MockStorage) HasSkill(_param0 string) bool {
	ret := _m.ctrl.Call(_m, "HasSkill", _param0)
	ret0, _ := ret[0].(bool)
	return ret0
}

func (_mr *_MockStorageRecorder) HasSkill(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "HasSkill", arg0)
}

func (_m *MockStorage) AddSkill(_param0 string) (bool, error) {
	ret := _m.ctrl.Call(_m, "AddSkill", _param0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockStorageRecorder) AddSkill(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AddSkill", arg0)
}

func (_m *MockStorage) HasJobWithUrl(_param0 string) bool {
	ret := _m.ctrl.Call(_m, "HasJobWithUrl", _param0)
	ret0, _ := ret[0].(bool)
	return ret0
}

func (_mr *_MockStorageRecorder) HasJobWithUrl(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "HasJobWithUrl", arg0)
}

func (_m *MockStorage) AddJob(_param0 structures.JobDetail) {
	_m.ctrl.Call(_m, "AddJob", _param0)
}

func (_mr *_MockStorageRecorder) AddJob(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AddJob", arg0)
}

func (_m *MockStorage) GetJobs(_param0 string, _param1 int, _param2 int) ([]structures.JobDetail, int64) {
	ret := _m.ctrl.Call(_m, "GetJobs", _param0, _param1, _param2)
	ret0, _ := ret[0].([]structures.JobDetail)
	ret1, _ := ret[1].(int64)
	return ret0, ret1
}

func (_mr *_MockStorageRecorder) GetJobs(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetJobs", arg0, arg1, arg2)
}

func (_m *MockStorage) GetSkills(_param0 int, _param1 int) []map[string]string {
	ret := _m.ctrl.Call(_m, "GetSkills", _param0, _param1)
	ret0, _ := ret[0].([]map[string]string)
	return ret0
}

func (_mr *_MockStorageRecorder) GetSkills(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetSkills", arg0, arg1)
}
